### Imports

In [1]:
import chromadb
import random
import time
import pandas as pd
from pathlib import Path
import re
import json
import subprocess
from collections import Counter
from sentence_transformers import SentenceTransformer
from youtube_transcript_api import YouTubeTranscriptApi
from langchain_ollama import ChatOllama, OllamaLLM
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_core.language_models.chat_models import BaseChatModel

### Setup

In [22]:
PLAYLIST_URL = "https://www.youtube.com/playlist?list=PLk1fjOl39-50kWobutO8NVFzbw9PHtbbg"

model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
api = YouTubeTranscriptApi()

client = chromadb.PersistentClient(path="./chroma_easy_german")
col = client.get_or_create_collection(
    "easy_german_a1_multi",
    metadata={"hnsw:space": "cosine"}
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

### Helper Functions

In [23]:
def is_subtitles_disabled(e: Exception) -> bool:
    return "subtitles are disabled" in str(e).lower()

def is_no_transcript(e: Exception) -> bool:
    return "no transcripts were found" in str(e).lower()

In [24]:
def is_ip_block_error(e: Exception) -> bool:
    msg = str(e).lower()
    return (
        "blocking requests from your ip" in msg
        or "requestblocked" in msg
        or "ipblocked" in msg
        or "too many requests" in msg
        or "toomanyrequests" in msg
    )

In [25]:
def fetch_with_backoff(video_id: str, languages=("de",), max_retries=6):
    delay = 20.0
    for attempt in range(max_retries):
        try:
            return api.fetch(video_id, languages=list(languages))
        except Exception as e:
            # If it's NOT an IP-block style error, bubble up (subtitles disabled, no transcript, etc.)
            if not is_ip_block_error(e):
                raise

            sleep_s = delay + random.uniform(0, 1.5)
            print(f"[BLOCKED] {video_id} — sleeping {sleep_s:.1f}s (attempt {attempt+1}/{max_retries})")
            time.sleep(sleep_s)
            delay *= 2

    raise RuntimeError(f"Still blocked after {max_retries} retries for {video_id}")

In [26]:
def get_playlist_entries(playlist_url: str):
    """
    Returns a list of dicts: 
    [{"id": "...", "title": "...", "url": "..."}]
    Uses yt-dlp.
    """
    cmd = [
        "yt-dlp",
        "--flat-playlist",
        "--dump-single-json",
        playlist_url,
    ]
    out = subprocess.check_output(cmd, text=True)
    data = json.loads(out)

    entries = []
    for e in data.get("entries", []):
        vid = e.get("id")
        if not vid:
            continue
        entries.append({
            "id": vid,
            "title": e.get("title", ""),
            "url": f"https://www.youtube.com/watch?v={vid}",
        })
    return entries

In [27]:
def get_playlist_entries_from_csv(path: str):
    df = pd.read_csv(path)

    entries = []
    for _, row in df.iterrows():
        entries.append({
            "id": row["id"],
            "title": row.get("title", ""),
            "url": row.get("url", f"https://www.youtube.com/watch?v={row['id']}")
        })

    return entries

In [48]:
def merge_transcript_chunks(
    chunks,
    max_chars=900,
    min_chars=300
    ):
    """
    Merge micro transcript segments into RAG-sized
    chunks while preserving timestamps.
    """
    merged = []
    buf_text = []
    buf_start = None
    buf_end = None
    
    for chunk in chunks:
        t = chunk["text"].strip()
        if not t:
            continue
        if buf_start is None:
            buf_start = chunk["start"]
            
        candidate = (" ".join(buf_text + [t])).strip()
    
        if len(candidate) < max_chars:
            buf_text.append(t)
            buf_end = chunk["end"]
        else:
            if buf_text:
                merged.append({
                    "text": " ".join(buf_text).strip(),
                    "start": buf_start,
                    "end": buf_end
                            })
            buf_text = [t]
            buf_start = chunk["start"]
            buf_end = chunk["end"]
            
    if buf_text:
        merged.append({
            "text": " ".join(buf_text).strip(),
            "start": buf_start,
            "end": buf_end})
    
    merged = [m for m in merged if len(m["text"]) >= min_chars]
    return merged

### Get entries to parse the videos

In [ ]:
# entries = get_playlist_entries(PLAYLIST_URL)
entries = get_playlist_entries_from_csv("entries.csv")

In [30]:
print(entries)

[{'id': 'huwi-cjPPXU', 'title': 'Introduce Yourself in Slow German | Super Easy German 258', 'url': 'https://www.youtube.com/watch?v=huwi-cjPPXU'}, {'id': 'Yaelm87PTvg', 'title': 'Introduce yourself in German (for absolute beginners) | Super Easy German (76)', 'url': 'https://www.youtube.com/watch?v=Yaelm87PTvg'}, {'id': 'hAkxKMlYUI4', 'title': 'German Alphabet & Pronunciation - Full Guide | Super Easy German 253', 'url': 'https://www.youtube.com/watch?v=hAkxKMlYUI4'}, {'id': 'LQiHX6OY_BI', 'title': 'Our Morning Routine in Slow German | Super Easy German 232', 'url': 'https://www.youtube.com/watch?v=LQiHX6OY_BI'}, {'id': 'aRlakaPVrEw', 'title': 'Learn Basic German Greetings & Farewells in Slow German | Super Easy German 274', 'url': 'https://www.youtube.com/watch?v=aRlakaPVrEw'}, {'id': '9h8p08qziG0', 'title': 'Conjugation of regular verbs: Sagen, Machen, Hören | Super Easy German (83)', 'url': 'https://www.youtube.com/watch?v=9h8p08qziG0'}, {'id': 'uO0jWxhVW1A', 'title': 'Easy German - Basic Conversation Phrases 1', 'url': 'https://www.youtube.com/watch?v=uO0jWxhVW1A'}, {'id': 'QNq1Xp6DgJw', 'title': 'Easy German - Basic Conversation Phrases 2', 'url': 'https://www.youtube.com/watch?v=QNq1Xp6DgJw'}, {'id': 'Q3eCDhwMRv8', 'title': 'How to learn the German Plural endings | Super Easy German (127)', 'url': 'https://www.youtube.com/watch?v=Q3eCDhwMRv8'}, {'id': 'tNrwiUGHMiU', 'title': 'Emotions in Slow German | Super Easy German 263', 'url': 'https://www.youtube.com/watch?v=tNrwiUGHMiU'}, {'id': 'MqqHc6lRQG4', 'title': 'Winter in Berlin in Slow German | Super Easy German 273', 'url': 'https://www.youtube.com/watch?v=MqqHc6lRQG4'}, {'id': 'r94aqLUO0wo', 'title': 'Introduce yourself in Slow German | Super Easy German (1)', 'url': 'https://www.youtube.com/watch?v=r94aqLUO0wo'}, {'id': 'QCGdeH4hYdo', 'title': 'Counting in German from 1 - 100 | Super Easy German 178', 'url': 'https://www.youtube.com/watch?v=QCGdeH4hYdo'}, {'id': 'NsqA8_SmdVI', 'title': 'How to Tell the Time in German | Super Easy German 183', 'url': 'https://www.youtube.com/watch?v=NsqA8_SmdVI'}, {'id': 'o-Zu-bUlPb4', 'title': 'Possessive Pronouns in German | Super Easy German 223', 'url': 'https://www.youtube.com/watch?v=o-Zu-bUlPb4'}, {'id': 'ITjyfCAspco', 'title': 'How to Remember Possessive Article Endings | Super Easy German 225', 'url': 'https://www.youtube.com/watch?v=ITjyfCAspco'}, {'id': '8QTb4is_fKw', 'title': 'Hoch, höher am höchsten! | Super Easy German (63)', 'url': 'https://www.youtube.com/watch?v=8QTb4is_fKw'}, {'id': 'RvcmpwHG1eQ', 'title': 'The Weather | Super Easy German (14)', 'url': 'https://www.youtube.com/watch?v=RvcmpwHG1eQ'}, {'id': 'OFSHdj_2FQA', 'title': 'Ordering in a Restaurant in Slow German | Super Easy German 236', 'url': 'https://www.youtube.com/watch?v=OFSHdj_2FQA'}, {'id': 'h5085YiFRnI', 'title': 'How to order drinks in German | Super Easy German (109)', 'url': 'https://www.youtube.com/watch?v=h5085YiFRnI'}, {'id': 'qYtsk5yH_nw', 'title': 'Our Lunch Break in Slow German | Super Easy German 265', 'url': 'https://www.youtube.com/watch?v=qYtsk5yH_nw'}, {'id': 'jUOvnHOsvXM', 'title': 'How to order Coffee in Germany? | Super Easy German (99)', 'url': 'https://www.youtube.com/watch?v=jUOvnHOsvXM'}, {'id': '3a__H9ejF4s', 'title': 'Having Breakfast in Slow German | Super Easy German 233', 'url': 'https://www.youtube.com/watch?v=3a__H9ejF4s'}, {'id': 'D91icSuPYQ4', 'title': 'Supermarket in Slow German | Super Easy German 288', 'url': 'https://www.youtube.com/watch?v=D91icSuPYQ4'}, {'id': 'kQPvtHeUUfU', 'title': 'Typical German Dinner in Slow German | Super Easy German 254', 'url': 'https://www.youtube.com/watch?v=kQPvtHeUUfU'}, {'id': 'bonBD3n2cy8', 'title': 'What Germans Buy at the Supermarket | Easy German 362', 'url': 'https://www.youtube.com/watch?v=bonBD3n2cy8'}, {'id': 'yCV4h5kDwbM', 'title': 'Grocery shopping in German | Super Easy German (33)', 'url': 'https://www.youtube.com/watch?v=yCV4h5kDwbM'}, {'id': 'kcixi0Vfg-I', 'title': 'Our Daily Chores in Slow German | Super Easy German 249', 'url': 'https://www.youtube.com/watch?v=kcixi0Vfg-I'}, {'id': 'N9iYnpvkOcA', 'title': 'Learning Fruits in German | Super Easy German (45)', 'url': 'https://www.youtube.com/watch?v=N9iYnpvkOcA'}, {'id': 'hunvSsyEeBU', 'title': 'Imperatives: How to Phrase Orders and Requests in German | Super Easy German 180', 'url': 'https://www.youtube.com/watch?v=hunvSsyEeBU'}, {'id': 'r8HiWsBe5ko', 'title': '100 Words You Should Know When Coming to Germany | Super Easy German 203', 'url': 'https://www.youtube.com/watch?v=r8HiWsBe5ko'}, {'id': 'KoupCFKNXUo', 'title': 'Small Talk (in Slow German) | Easy German Live', 'url': 'https://www.youtube.com/watch?v=KoupCFKNXUo'}, {'id': 'eKLtI48rvtw', 'title': 'Top 50 Everyday Objects in Slow German | Super Easy German 244', 'url': 'https://www.youtube.com/watch?v=eKLtI48rvtw'}, {'id': '3MiTl52EKd8', 'title': 'Easy German Basic Phrases - Introducing Yourself', 'url': 'https://www.youtube.com/watch?v=3MiTl52EKd8'}, {'id': 'qSGUD9WYRwE', 'title': 'Walk Through Our Neighborhood in Slow German | Super Easy German 228', 'url': 'https://www.youtube.com/watch?v=qSGUD9WYRwE'}, {'id': 'qnLj-KV9WaQ', 'title': 'How to describe your body in German | Super Easy German (117)', 'url': 'https://www.youtube.com/watch?v=qnLj-KV9WaQ'}, {'id': '5LsSHezUUKQ', 'title': 'German Clothing Vocabulary | Super Easy German 170', 'url': 'https://www.youtube.com/watch?v=5LsSHezUUKQ'}, {'id': 'xbWOui-V-U4', 'title': 'All German Cases | Super Easy German (55)', 'url': 'https://www.youtube.com/watch?v=xbWOui-V-U4'}, {'id': 'cYMSTF8iQWw', 'title': 'Easy German Cases - German Cases by Pia and Lisa', 'url': 'https://www.youtube.com/watch?v=cYMSTF8iQWw'}, {'id': 'aZTUJm8O2Ds', 'title': '12 Verbs + Accusative Beginners Should Know | Super Easy German 259', 'url': 'https://www.youtube.com/watch?v=aZTUJm8O2Ds'}, {'id': 'Uab5EC28h1w', 'title': 'How to use Accusative and Dative in German | Super Easy German (122)', 'url': 'https://www.youtube.com/watch?v=Uab5EC28h1w'}, {'id': 'IQvtG8deSe0', 'title': 'Easy German Cases - Nominativ (Super SLOMO with Pia and Lisa)', 'url': 'https://www.youtube.com/watch?v=IQvtG8deSe0'}, {'id': '1cREa7o2EPQ', 'title': 'German cases: Accusative | Easy German 127', 'url': 'https://www.youtube.com/watch?v=1cREa7o2EPQ'}, {'id': 'A3kDyxMO2xI', 'title': 'GERMAN ACCUSATIVE | Super Easy German (16)', 'url': 'https://www.youtube.com/watch?v=A3kDyxMO2xI'}, {'id': 'ZgmVwPjTtM4', 'title': 'What do I see in the Streets (accusative exercise) | Super Easy German (41)', 'url': 'https://www.youtube.com/watch?v=ZgmVwPjTtM4'}, {'id': 'MppF9phHkzI', 'title': 'German Cases Drill (Nominative + Accusative) | Super Easy German (121)', 'url': 'https://www.youtube.com/watch?v=MppF9phHkzI'}, {'id': 'CDgG2K7Kbbs', 'title': 'Präpositionen mit Dativ | Super Easy German (40)', 'url': 'https://www.youtube.com/watch?v=CDgG2K7Kbbs'}, {'id': 'GT6ZDpB_7rA', 'title': 'Mit + Dative | Super Easy German (72)', 'url': 'https://www.youtube.com/watch?v=GT6ZDpB_7rA'}, {'id': 'tj_YhY2RMxs', 'title': 'Irregular Verbs: Haben, Sein, Gehen | Super Easy German (90)', 'url': 'https://www.youtube.com/watch?v=tj_YhY2RMxs'}, {'id': 'VTN-Qys9fCA', 'title': '100 Everyday Sentences with the Verb “Haben” | Easy German 589', 'url': 'https://www.youtube.com/watch?v=VTN-Qys9fCA'}, {'id': 'wqw336j-F3E', 'title': 'German Verbs: Sein | Super Easy German (149)', 'url': 'https://www.youtube.com/watch?v=wqw336j-F3E'}, {'id': 'an232kkTEMk', 'title': '102 Everyday Sentences With the Verb “Sein” | Easy German 591', 'url': 'https://www.youtube.com/watch?v=an232kkTEMk'}, {'id': 'J4Y5os6gHxI', 'title': 'German Verbs: Gehen | Super Easy German (147)', 'url': 'https://www.youtube.com/watch?v=J4Y5os6gHxI'}, {'id': 'Bo3YyLmzS9E', 'title': 'German Verbs: Fahren | Super Easy German (146)', 'url': 'https://www.youtube.com/watch?v=Bo3YyLmzS9E'}, {'id': 'WxK_boaYVik', 'title': 'German Verbs: Finden | Super Easy German (151)', 'url': 'https://www.youtube.com/watch?v=WxK_boaYVik'}, {'id': 'D12qgTxjC3c', 'title': 'German Verbs: Geben | Super Easy German (148)', 'url': 'https://www.youtube.com/watch?v=D12qgTxjC3c'}, {'id': 'AOQ5X-ayjWE', 'title': 'German Verbs: Wissen | Super Easy German (153)', 'url': 'https://www.youtube.com/watch?v=AOQ5X-ayjWE'}, {'id': 'lZXGpjKHHo8', 'title': 'Irregular Verbs: Mögen | Super Easy German (103)', 'url': 'https://www.youtube.com/watch?v=lZXGpjKHHo8'}, {'id': 'o7cMNtORT4I', 'title': 'German Verbs: Machen | Super Easy German (142)', 'url': 'https://www.youtube.com/watch?v=o7cMNtORT4I'}, {'id': 'OqvuldWHr_s', 'title': '"Wollen" vs. "Mögen" vs. "Möchten" | Super Easy German 192', 'url': 'https://www.youtube.com/watch?v=OqvuldWHr_s'}, {'id': '6lTltCmgrCk', 'title': 'German Verbs: Können | Super Easy German (138)', 'url': 'https://www.youtube.com/watch?v=6lTltCmgrCk'}, {'id': 'dV54jc8K6MU', 'title': '16 Verbs + Prepositions You Should Know (A1 Level) | Super Easy German 229', 'url': 'https://www.youtube.com/watch?v=dV54jc8K6MU'}, {'id': 'K1eejivNkRQ', 'title': 'Separable verbs in German | Super Easy German (31)', 'url': 'https://www.youtube.com/watch?v=K1eejivNkRQ'}, {'id': 'fB12-T5jC30', 'title': 'These Verbs Always Use The Simple Past | Super Easy German 191', 'url': 'https://www.youtube.com/watch?v=fB12-T5jC30'}, {'id': '0q8ceeaEI68', 'title': 'Perfect Tense in German | Super Easy German (26)', 'url': 'https://www.youtube.com/watch?v=0q8ceeaEI68'}, {'id': '4gl3-i0KXqY', 'title': '10 German Verbs that Change Vowels (Strong Verbs for Beginners) | Super Easy German 220', 'url': 'https://www.youtube.com/watch?v=4gl3-i0KXqY'}, {'id': 'kYEBu6dG2MM', 'title': 'A Day in our Office in slow German | Super Easy German 235', 'url': 'https://www.youtube.com/watch?v=kYEBu6dG2MM'}, {'id': 'SzfIlzLFmn0', 'title': 'Wie vs. Als | Super Easy German (88)', 'url': 'https://www.youtube.com/watch?v=SzfIlzLFmn0'}, {'id': '7GH7AFxA3gY', 'title': 'MIT vs. OHNE | Super Easy German 201', 'url': 'https://www.youtube.com/watch?v=7GH7AFxA3gY'}, {'id': 'fa9K07uIrOo', 'title': 'German Prepositions: BEI | Super Easy German (39)', 'url': 'https://www.youtube.com/watch?v=fa9K07uIrOo'}, {'id': 'vC_7XBaqsc4', 'title': 'Kein vs. Nicht | Easy German 341', 'url': 'https://www.youtube.com/watch?v=vC_7XBaqsc4'}, {'id': 'ZqCevnsyMAQ', 'title': 'Our Vacation in Slow German | Super Easy German 234', 'url': 'https://www.youtube.com/watch?v=ZqCevnsyMAQ'}, {'id': 'hxGSArgzNN8', 'title': 'Sports | Super Easy German (3)', 'url': 'https://www.youtube.com/watch?v=hxGSArgzNN8'}, {'id': 'T-AtG9BvwHg', 'title': '"Ach" Explained | Super Easy German (126)', 'url': 'https://www.youtube.com/watch?v=T-AtG9BvwHg'}, {'id': 'f4V2LnkGkLg', 'title': 'Pia and Lisa go shopping | Easy German 85', 'url': 'https://www.youtube.com/watch?v=f4V2LnkGkLg'}, {'id': 'uqhNQ7fiQSQ', 'title': 'NA JA - Explained | Super Easy German (125)', 'url': 'https://www.youtube.com/watch?v=uqhNQ7fiQSQ'}, {'id': 'TDRNIkVE4bw', 'title': 'Berlin in December in Slow German | Super Easy German 268', 'url': 'https://www.youtube.com/watch?v=TDRNIkVE4bw'}, {'id': 'XiBt9Nm0PHU', 'title': 'Clothing Vocabulary in Slow German | Super Easy German 270', 'url': 'https://www.youtube.com/watch?v=XiBt9Nm0PHU'}, {'id': 'jN4Ike7iBVk', 'title': 'At the Mall in Slow German | Super Easy German 276', 'url': 'https://www.youtube.com/watch?v=jN4Ike7iBVk'}, {'id': 'StmjIvwtKlg', 'title': 'At The Train Station in Slow German | Super Easy German 279', 'url': 'https://www.youtube.com/watch?v=StmjIvwtKlg'}, {'id': 'YWn2kAjbhrA', 'title': 'German Dative Case: 15 Simple Verbs That Always Take the Dative | Super Easy German 215', 'url': 'https://www.youtube.com/watch?v=YWn2kAjbhrA'}, {'id': 'LwJfk1NUeg4', 'title': '10 Min Conversation in Slow German | Super Easy German 287', 'url': 'https://www.youtube.com/watch?v=LwJfk1NUeg4'}, {'id': 'jWDuDRHZvk8', 'title': 'German Verbs: Haben | Super Easy German (131)', 'url': 'https://www.youtube.com/watch?v=jWDuDRHZvk8'}]

In [31]:
df = pd.read_csv("entries.csv")
id2title = dict(zip(df["id"], df["title"]))

### Loop through videos

In [32]:
# Get all existing video_ids in collection
existing = col.get(include=["metadatas"])

existing_video_ids = set()

for meta in existing["metadatas"]:
    if meta and "video_id" in meta:
        existing_video_ids.add(meta["video_id"])

print("Already indexed videos:", len(existing_video_ids))

Already indexed videos: 80

In [33]:
for idx, e in enumerate(entries, start=1):
    video_id = e["id"]
    title = e["title"]

    if video_id in existing_video_ids:
        print(f"[{idx}/{len(entries)}] SKIP {video_id} — already indexed")
        continue

    try:
        transcript_de = fetch_with_backoff(video_id, languages=("de",))
    except Exception as e:
        print(f"SKIP {video_id}: {e}")
        continue
    # polite pacing between successful requests too
    time.sleep(random.uniform(1.5, 10.0))
        
    structured_chunks = [
    {"text": chunk.text,
     "start": chunk.start,
     "end": chunk.start + chunk.duration
     } 
    for chunk in transcript_de
    ]
    
    merged_chunks = merge_transcript_chunks(chunks=structured_chunks, max_chars=600)
    if not merged_chunks:
        print(f"[{idx}/{len(entries)}] SKIP {video_id} — merged_chunks empty")
        continue
    
    docs = [c["text"] for c in merged_chunks]
    metas = [
    {
        "video_id": video_id,
        "title": title,
        "lang": "de",
        "start": c["start"],
        "end": c["end"],
        "playlist": "easy_german_a1",
    } 
    for c in merged_chunks
    ]
    
    embs = model.encode(
    docs,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
    ).tolist()

    ids = [f"{video_id}_{i}" for i in range(len(docs))]

    if hasattr(col, "upsert"):
        col.upsert(
            documents=docs,
            embeddings=embs,
            ids=ids,
            metadatas=metas
            )
    else:
        col.add(
            documents=docs,
            embeddings=embs,
            ids=ids,
            metadatas=metas
            )
        
    print(f"[{idx}/{len(entries)}] OK {video_id} — {len(docs)} chunks — {title}")

[1/83] SKIP huwi-cjPPXU — already indexed
[2/83] SKIP Yaelm87PTvg — already indexed
[3/83] SKIP hAkxKMlYUI4 — already indexed
[4/83] SKIP LQiHX6OY_BI — already indexed
[5/83] SKIP aRlakaPVrEw — already indexed
[6/83] SKIP 9h8p08qziG0 — already indexed
[7/83] SKIP uO0jWxhVW1A — already indexed
[8/83] SKIP QNq1Xp6DgJw — already indexed
[9/83] SKIP Q3eCDhwMRv8 — already indexed
[10/83] SKIP tNrwiUGHMiU — already indexed
[11/83] SKIP MqqHc6lRQG4 — already indexed
[12/83] SKIP r94aqLUO0wo — already indexed
[13/83] SKIP QCGdeH4hYdo — already indexed
[14/83] SKIP NsqA8_SmdVI — already indexed
[15/83] SKIP o-Zu-bUlPb4 — already indexed
SKIP ITjyfCAspco:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=ITjyfCAspco! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
[17/83] SKIP 8QTb4is_fKw — already indexed
[18/83] SKIP RvcmpwHG1eQ — already indexed
[19/83] SKIP OFSHdj_2FQA — already indexed
[20/83] SKIP h5085YiFRnI — already indexed
[21/83] SKIP qYtsk5yH_nw — already indexed
[22/83] SKIP jUOvnHOsvXM — already indexed
[23/83] SKIP 3a__H9ejF4s — already indexed
[24/83] SKIP D91icSuPYQ4 — already indexed
[25/83] SKIP kQPvtHeUUfU — already indexed
[26/83] SKIP bonBD3n2cy8 — already indexed
[27/83] SKIP yCV4h5kDwbM — already indexed
[28/83] SKIP kcixi0Vfg-I — already indexed
[29/83] SKIP N9iYnpvkOcA — already indexed
[30/83] SKIP hunvSsyEeBU — already indexed
[31/83] SKIP r8HiWsBe5ko — already indexed
[32/83] SKIP KoupCFKNXUo — already indexed
[33/83] SKIP eKLtI48rvtw — already indexed
[34/83] SKIP 3MiTl52EKd8 — already indexed
[35/83] SKIP qSGUD9WYRwE — already indexed
[36/83] SKIP qnLj-KV9WaQ — already indexed
[37/83] SKIP 5LsSHezUUKQ — already indexed
[38/83] SKIP xbWOui-V-U4 — already indexed
[39/83] SKIP cYMSTF8iQWw — already indexed
[40/83] SKIP aZTUJm8O2Ds — already indexed
[41/83] SKIP Uab5EC28h1w — already indexed
[42/83] SKIP IQvtG8deSe0 — already indexed
[43/83] SKIP 1cREa7o2EPQ — already indexed
[44/83] SKIP A3kDyxMO2xI — already indexed
[45/83] SKIP ZgmVwPjTtM4 — already indexed
[46/83] SKIP MppF9phHkzI — already indexed
[47/83] SKIP CDgG2K7Kbbs — already indexed
[48/83] SKIP GT6ZDpB_7rA — already indexed
[49/83] SKIP tj_YhY2RMxs — already indexed
[50/83] SKIP VTN-Qys9fCA — already indexed
[51/83] SKIP wqw336j-F3E — already indexed
[52/83] SKIP an232kkTEMk — already indexed
[53/83] SKIP J4Y5os6gHxI — already indexed
[54/83] SKIP Bo3YyLmzS9E — already indexed
[55/83] SKIP WxK_boaYVik — already indexed
[56/83] SKIP D12qgTxjC3c — already indexed
[57/83] SKIP AOQ5X-ayjWE — already indexed
[58/83] SKIP lZXGpjKHHo8 — already indexed
[59/83] SKIP o7cMNtORT4I — already indexed
[60/83] SKIP OqvuldWHr_s — already indexed
[61/83] SKIP 6lTltCmgrCk — already indexed
[62/83] SKIP dV54jc8K6MU — already indexed
[63/83] SKIP K1eejivNkRQ — already indexed
[64/83] SKIP fB12-T5jC30 — already indexed
[65/83] SKIP 0q8ceeaEI68 — already indexed
[66/83] SKIP 4gl3-i0KXqY — already indexed
SKIP kYEBu6dG2MM:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=kYEBu6dG2MM! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
[68/83] SKIP SzfIlzLFmn0 — already indexed
[69/83] SKIP 7GH7AFxA3gY — already indexed
[70/83] SKIP fa9K07uIrOo — already indexed
[71/83] SKIP vC_7XBaqsc4 — already indexed
[72/83] SKIP ZqCevnsyMAQ — already indexed
SKIP hxGSArgzNN8:
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=hxGSArgzNN8! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['de']

For this video (hxGSArgzNN8) transcripts are available in the following languages:

(MANUALLY CREATED)
None

(GENERATED)
 - en ("English (auto-generated)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - ar ("Arabic")
 - zh-Hant ("Chinese (Traditional)")
 - nl ("Dutch")
 - fr ("French")
 - de ("German")
 - hi ("Hindi")
 - id ("Indonesian")
 - it ("Italian")
 - ja ("Japanese")
 - ko ("Korean")
 - pt ("Portuguese")
 - ru ("Russian")
 - es ("Spanish")
 - th ("Thai")
 - uk ("Ukrainian")
 - vi ("Vietnamese")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
[74/83] SKIP T-AtG9BvwHg — already indexed
[75/83] SKIP f4V2LnkGkLg — already indexed
[76/83] SKIP uqhNQ7fiQSQ — already indexed
[77/83] SKIP TDRNIkVE4bw — already indexed
[78/83] SKIP XiBt9Nm0PHU — already indexed
[79/83] SKIP jN4Ike7iBVk — already indexed
[80/83] SKIP StmjIvwtKlg — already indexed
[81/83] SKIP YWn2kAjbhrA — already indexed
[82/83] SKIP LwJfk1NUeg4 — already indexed
[83/83] SKIP jWDuDRHZvk8 — already indexed

In [ ]:
def return_context(query: str, k: int=3):
    '''
    A function to return the context of the k closest based on cosine similarity
    '''
    q_emb = model.encode([query], normalize_embeddings=True).tolist()

    res = col.query(query_embeddings=q_emb, n_results=5)

    ctx = []

    for meta, doc in zip(res["metadatas"][0], res["documents"][0]):
        vid = meta.get("video_id")
        title = meta.get("title") or id2title.get(vid) or vid or "Unknown"
        ctx.append(f"{title} [{meta.get('start',0):.1f}s–{meta.get('end',0):.1f}s]{doc}")
    return "\n\n".join(ctx)

### Creating the LLM (coach layer)

In [61]:
query = "How do Germans apologize in daily life?"

In [ ]:
llm_coach_chat = ChatOllama(
    model="llama3.1:latest", 
    temperature=0, 
    num_ctx=1024,
    num_predict=120,
    )

llm_fast = ChatOllama(
    model="qwen2.5:3b",
    temperature=0,
    num_ctx=1024,
    num_predict=120
)

### Tools for my agent to call

In [63]:
def tutor_a1(llm, user_query: str, k: int = 2) -> str:
    t0 = time.time()
    ctx = return_context(user_query, k=k)
    t1 = time.time()
    ctx = return_context(user_query, k=k)
    ctx = ctx[:1200]

    system = SystemMessage(content="""
You are a structured German tutor (A1).
Return EXACTLY:
- 3 phrases about the query (DE—EN)
- 2 examples (DE—EN)
- 1 short follow up
Maximum 80 words total.
Do not add explanations.
""".strip())

    user = HumanMessage(content=f"""
Question: {user_query}

Context:
{ctx}
""".strip())

    out = llm.invoke([system, user])
    t2 = time.time()
    print(f"retrieval: {t1-t0:.2f}s | llm: {t2-t1:.2f}s | ctx_chars={len(ctx)}")
    return out.content if hasattr(out, "content") else out

print(tutor_a1(llm_fast, query, k=2))

retrieval: 0.14s | llm: 11.98s | ctx_chars=1200
Phrases:
1. Germans often say "Es tut mir leid" when they apologize.
2. They might add "Vielen Dank für eure Verständnis."
3. Sometimes, they use "Ich schätze es sehr."

Examples:
1. Ich habe vergessen zu sagen, vielen Dank für euer Verständnis.
2. Es tut mir leid, dass ich spät gekommen bin.

Follow up:
Haben Sie noch Fragen zum Thema Deutsch oder Apologetik?

In [64]:
t0 = time.time()
ans = tutor_a1(llm_fast, query)
t1 = time.time()

print("seconds:", t1 - t0)
print("tokens approx:", len(ans.split()))
print("approx tok/sec:", len(ans.split()) / (t1 - t0))

retrieval: 0.20s | llm: 15.47s | ctx_chars=1200
seconds: 15.665279150009155
tokens approx: 70
approx tok/sec: 4.468480856912089

retrieval: 0.14s | llm: 22.28s | ctx_chars=1200
seconds: 22.42194128036499
tokens approx: 60
approx tok/sec: 2.6759502778888424

### Building german agent

In [ ]:
def german_agent(llm, user_query: str, mode: str='tutor', level: str='a1', k: int=2):
    """
    Main orchestration function for the German learning agent.

    This function:
    - Selects the appropriate instructional mode.
    - Adjusts output complexity based on CEFR level.
    - Processes the user query.
    - Retrieves and incorporates relevant transcript context.

    Parameters
    ----------
    mode : {'tutor', 'vocab', 'grammar', 'quiz'}
        Determines the type of learning interaction:
        - 'tutor'   : Structured explanation and guided practice
        - 'vocab'   : Vocabulary extraction with examples
        - 'grammar' : Grammar explanation and pattern breakdown
        - 'quiz'    : Assessment-style exercises

    level : {'A1', 'A2', 'B1', 'B2', 'C1', 'C2'}
        CEFR proficiency level used to control linguistic complexity.

    user_query : str
        The user’s question or topic of interest.

    Returns
    -------
    str
        A structured response generated by the language model
        according to the selected mode and level.
    """
    
    templates = {
    "tutor": f"""
        You are a supportive German language tutor teaching at {level} level.

        Follow these steps:

        1. Answer the student's question clearly.
        2. Explain why the answer is correct.
        3. Use relevant examples from the provided context.
        4. Give 2–3 short German examples with English translations.
        5. End with one guiding follow-up question to encourage thinking.

        Use simple language appropriate for {level}.
        Respond only in English and German.
        Do not mention sources or timestamps.
            """,

     "vocab": f"""
        You are a structured German vocabulary trainer ({level} level).
        Return EXACTLY:
        - 5 most key related to the query (DE-EN)
        - 1 example sentence for each from the context (DE-EN)
        Maximum 80 words total.
        Do not add explanations.
            """,
        
    "grammar": f"""
        You are a structured German grammar trainer ({level} level).
        Return EXACTLY:
        - 3 example sentences from the context (DE-EN)
        - A short grammar explanation (DE-EN)
        Maximum 80 words total.
            """,
        
    "quiz": f"""
        You are a structured German quiz generator ({level} level).
        Return EXACTLY:
        - 3 short quiz questions from the context (DE—EN)
        Maximum 80 words total.
        Do not add explanations.
            """
    }
                                
    if mode not in templates:
        raise ValueError(f"Invalid mode: {mode}")    

    ctx = return_context(query, k=k)
    
    system_text = templates[mode].strip()
        
    system = SystemMessage(content = system_text)
            
    user = HumanMessage(content=f"""
                                Question: {user_query}

                                Context:
                                {ctx}
                                """.strip())

    out = llm.invoke([system, user])
    return out.content if hasattr(out, "content") else out

In [80]:
query = "What is the difference of accusative and nominative?"

print(german_agent(llm_fast, query, 'tutor', 'A1'))

print("\n-------------------------------------\n")

print(german_agent(llm_coach_chat, query, 'tutor', 'A1'))

- Akkusativ — Nominativ — Der Akkusativ und der Nominativ sind zwei Fälle im Deutschen, die unterschiedliche Verwendung haben.
- Akkusativ — Accusative — In der Sprache wird der Akkusativ für den Zweck verwendet, während der Nominativ oft als Objekt oder Ziel fungiert.
- German sentence — English translation
Akkusativ und Nominativ sind zwei Fälle im Deutschen, die unterschiedliche Verwendung haben. Explanation: Akkusativ wird für den Zweck verwendet, während der Nominativ oft als Objekt oder

-------------------------------------

- Nominativ (Nominative) — Subjekt (Subject)
- Akkusativ (Accusative) — Objekt (Object)

Explanation:
In German, the nominative case is used for the subject of a sentence, while the accusative case is used for the direct object. For example: "Der Hund biss den Mann" (The dog bit the man). Here, "der Hund" is in the nominative case because it's the subject, and "den Mann" is in the accusative case because it's the direct object.

Follow-up quiz:
What is

#### Some tests

In [81]:
llm_fast = ChatOllama(
    model="qwen2.5:3b",
    temperature=0,
    num_ctx=1024,
    num_predict=120
)

def clean_context(ctx):
    lines = ctx.split("\n")
    filtered = [
        line for line in lines
        if not ("|" in line and "[" in line)  # remove metadata lines
    ]
    return "\n".join(filtered)

def german_agent(llm, user_query: str, mode: str='tutor', level: str='a1', k: int=2):
    """
    Main orchestration function for the German learning agent.

    This function:
    - Selects the appropriate instructional mode.
    - Adjusts output complexity based on CEFR level.
    - Processes the user query.
    - Retrieves and incorporates relevant transcript context.

    Parameters
    ----------
    mode : {'tutor', 'vocab', 'grammar', 'quiz'}
        Determines the type of learning interaction:
        - 'tutor'   : Structured explanation and guided practice
        - 'vocab'   : Vocabulary extraction with examples
        - 'grammar' : Grammar explanation and pattern breakdown
        - 'quiz'    : Assessment-style exercises

    level : {'A1', 'A2', 'B1', 'B2', 'C1', 'C2'}
        CEFR proficiency level used to control linguistic complexity.

    user_query : str
        The user’s question or topic of interest.

    Returns
    -------
    str
        A structured response generated by the language model
        according to the selected mode and level.
    """
    
    templates = {
    "tutor": f"""
        You are a supportive German language tutor teaching at {level} level.

        Follow these steps:

        1. Answer the student's question clearly.
        2. Explain why the answer is correct.
        3. Use relevant examples from the provided context.
        4. Give 2–3 short German examples with English translations.
        5. End with one guiding follow-up question to encourage thinking.

        Use simple language appropriate for {level}.
        Respond only in English and German.
        Do not mention sources or timestamps.
            """,

     "vocab": f"""
        You MUST respond only in English and German.
        You are a structured German vocabulary trainer ({level} level).
        Return EXACTLY:
        - 5 most key related to the query (DE-EN)
        - 1 example sentence for each from the context (DE-EN)
        Maximum 80 words total.
        Do not add explanations.
            """,
        
    "grammar": f"""
        You MUST respond only in English and German.
        You are a structured German grammar trainer ({level} level).
        Return EXACTLY:
        - 3 example sentences from the context (DE-EN)
        - A short grammar explanation (DE-EN)
        Maximum 80 words total.
            """,
        
    "quiz": f"""
        You MUST respond only in English and German.
        You are a structured German quiz generator ({level} level).
        Return EXACTLY:
        - 3 short quiz questions from the context (DE—EN)
        Maximum 80 words total.
        Do not add explanations.
            """
    }
                                
    if mode not in templates:
        raise ValueError(f"Invalid mode: {mode}")    

    ctx = clean_context(return_context(user_query, k=k))
    ctx = ctx[:800]
    
    system_text = templates[mode].strip()
        
    system = SystemMessage(content = system_text)
            
    user = HumanMessage(content=f"""
                                Question: {user_query}

                                Context:
                                {ctx}
                                """.strip())

    out = llm.invoke([system, user])
    return out.content if hasattr(out, "content") else out


query = "What is the difference of accusative and nominative?"

t0 = time.time()
print(german_agent(llm_fast, query, 'tutor', 'A1'))
t1 = time.time()
print("seconds:", t1 - t0)
print("\n-------------------------------------\n")
print(german_agent(llm_coach_chat, query, 'tutor', 'A1'))
t2 = time.time()
print("seconds:", t2 - t1)

In German, "nominative" and "accusative" are cases used with nouns.

Nominative case:
- It's used when a noun is the subject of a sentence.
- Example: Ich esse Brot. (I eat bread.) Here, "Brot" is in nominative case because it's the main person or thing doing something.

Accusative case:
- It's used when a noun is the direct object of a verb.
- Example: Ich esse das Brot. (I eat the bread.) Here, "das Brot" is in accusative
seconds: 25.652050018310547

-------------------------------------

Don't worry, it's easy!

The main difference between accusative and nominative is how we use them to talk about people or things in a sentence.

**Nominative** is used for the subject of the sentence, which means the person or thing that does something. For example:

* Ich esse ein Sandwich. (I eat a sandwich.)
In this sentence, "Ich" (I) is the subject, so it's in nominative form.

**Accusative** is used for the object of the sentence, which means the person or thing that receives an action. For example
seconds: 93.29227328300476

### Creating the topics for other modes

I could have added the topics from the video, but they are a little messy

In [7]:

PATH = ("data/entries.csv")

# I made this simple, it's just titles
# We can make it more complex later
STOPWORDS = {"easy", "german", "learn", 
             "easygerman", "episode", 
             "video", "with", "in", "the",
             "a", "an", "and", "for", 
             "how", "to", "about"}

# Had to add this, or else the topics could be strange
TOPIC_RULES = {
    "Alphabet": ["alphabet", "letter", "letters", "pronunciation"],
    "Numbers": ["counting", "number", "numbers", "counter", "numeral", "numerals"],
    "Introductions": ["introduce", "introduction", "greetings", "greeting", "hello", "hi", "good morning", "pleasure"],
    "Verbs": ["verbs", "sein", "gehen", "fahren", "finden", "geben", "wissen", "machen", "haben", "können", "wollen", "mögen"],
    "Cases": ["case", "cases", "nominativ", "akkusativ", "accusative", "dative"],
    "Prepositions": ["preposition", "präpositionen", "mit", "bei", "ohne"],
    "Restaurant & Food": ["restaurant", "order", "coffee", "drinks", "breakfast", "lunch", "dinner"],
    "Daily Life": ["daily", "morning", "vacation", "winter", "berlin"],
    "Shopping": ["supermarket", "shopping", "grocery", "mall"],
    "Conversation": ["conversation", "small talk", "phrases", "greetings"],
    "Grammar": ["conjugation", "plural", "tense", "imperative"],
    "Vocabulary": ["vocabulary", "fruits", "clothing", "emotions"]
}

In [8]:
df = pd.read_csv(PATH)
df.head()

,id,title,url
0,huwi-cjPPXU,Introduce Yourself in Slow German | Super Easy...,https://www.youtube.com/watch?v=huwi-cjPPXU
1,Yaelm87PTvg,Introduce yourself in German (for absolute beg...,https://www.youtube.com/watch?v=Yaelm87PTvg
2,hAkxKMlYUI4,German Alphabet & Pronunciation - Full Guide |...,https://www.youtube.com/watch?v=hAkxKMlYUI4
3,LQiHX6OY_BI,Our Morning Routine in Slow German | Super Eas...,https://www.youtube.com/watch?v=LQiHX6OY_BI
4,aRlakaPVrEw,Learn Basic German Greetings & Farewells in Sl...,https://www.youtube.com/watch?v=aRlakaPVrEw

In [9]:
def assign_topic(title: str):
    """Function to assign a topic due to a video title

    Args:
        title (str): The video title from the dataset

    Returns:
        _type_: It return the topic of the title
    """
    title_lower = title.lower()

    for topic, keywords in TOPIC_RULES.items():
        if any(k in title_lower for k in keywords):
            return topic

    return "Other"

In [10]:
df["topic"] = df["title"].apply(assign_topic)
df.head()

,id,title,url,topic
0,huwi-cjPPXU,Introduce Yourself in Slow German | Super Easy...,https://www.youtube.com/watch?v=huwi-cjPPXU,Introductions
1,Yaelm87PTvg,Introduce yourself in German (for absolute beg...,https://www.youtube.com/watch?v=Yaelm87PTvg,Introductions
2,hAkxKMlYUI4,German Alphabet & Pronunciation - Full Guide |...,https://www.youtube.com/watch?v=hAkxKMlYUI4,Alphabet
3,LQiHX6OY_BI,Our Morning Routine in Slow German | Super Eas...,https://www.youtube.com/watch?v=LQiHX6OY_BI,Daily Life
4,aRlakaPVrEw,Learn Basic German Greetings & Farewells in Sl...,https://www.youtube.com/watch?v=aRlakaPVrEw,Introductions

In [13]:
df.to_csv(PATH, index=False)